[package]
name = "bitcoin-light-client-circuit"
version.workspace = true
edition.workspace = true

[dependencies]
bitcoin = { workspace = true, features = ["serde", "rand", "secp-recovery"] }
#secp256k1 = { version = "0.30.0" }
goat = { workspace = true }
bitcoin-script.workspace = true

bincode = "1.3.3"
# workspace
guest-executor = { workspace = true }
header-chain = { path = "../header-chain" }
commit-chain = { path = "../commit-chain" }

# Ziren
zkm-verifier = { git = "https://github.com/ProjectZKM/Ziren", package = "zkm-verifier" }
zkm-zkvm = { git = "https://github.com/ProjectZKM/Ziren", package = "zkm-zkvm", features = ["verify"] }

# Statically turns off logging
tracing = { workspace = true, features = ["max_level_trace"] }

alloy-primitives = { workspace = true, features = ["sha3-keccak", "map-foldhash", "serde"] }
revm-database-interface = { workspace = true, features = ["serde"]}

revm = { workspace = true, features = ["serde", "kzg-rs", "bn"], default-features = false }
sha2 = "0.10.8"
hex = "0.4.3"

prost = { version = "0.13", features = ["prost-derive"], default-features = false }
prost-derive = { version = "0.13", default-features = true }
base64 = "0.21"

serde = { workspace = true, features = ["derive"] }

cosmos-sdk-proto = { version = "0.27", default-features = false, features = ["serde"] }
tendermint = { git = "https://github.com/ProjectZKM/tendermint-rs", branch = "patch-0.40.3", default-features = false, features = ["secp256k1"] }
tendermint-light-client-verifier = { git = "https://github.com/ProjectZKM/tendermint-rs", branch = "patch-0.40.3", default-features = false, features = [
  "rust-crypto",
] }


[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0"
borsh = {version = "1.5.3", features = ["derive"] }
blake3 = "1.6.1"
zkm-sdk = { git = "https://github.com/ProjectZKM/Ziren" }

[build-dependencies]
prost-build = "0.13"
